language: python
cache: pip
python:
- "3.7"
- "3.8"
- "3.9"
- "3.10"

install:
- cp packaging/setup.py .
- pip install .

script:
- export PYTHONPATH=.:vendor
- export TEST_CONFIG=tests/config/travis.json
- python -m unittest discover tests
